### ISSUE TITLE
Error response 

### ISSUE THREAD

**Issue by hishampro5** [MostafaGad1911/QuranKareem-Service#5]
you should return error response on object not directly string "don't missing reader id",
it should be some like this :

Error Response
{
success : false
message : "don't missing reader id"
}

Success Response
{
success : true
message : "....."
data{...}
....
....
}

we need this to custom response and make one call api.

**Comment by hishampro5** [comment]
you should return error response on object not directly  string "don't missing reader id",
it should be some like this  : 

**Error Response** 
{
success : false
message : "don't missing reader id"
}

**Success Response**
{
success : true
message : "....."
data{...}
....
....
}

we need this to custom response and make one call api.

**Comment by hishampro5** [comment]
@MostafaGad1911

**Comment by MostafaGad1911** [comment]
thanks @hishampro5 appreciated for ur comment will be edited inshallah
